name: build-and-deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}  # Change from key to password
        source: "."
        target: "/var/www/3DVista"
    - name: SSH and rebuild container
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}  # Change from key to password
        script: |
          cd /var/www/3DVista
          docker stop 3dvista || true
          docker rm 3dvista || true
          docker build -t 3dvista .
          docker run -d -p 3000:3000 --name 3dvista 3dvista
