name: build-and-deploy-to-aws

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build Docker image
      run: docker build -t 3dvista .

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get ECR Repository URL
      id: ecr-repo-url
      run: |
        REPO_URI=$(aws ecr describe-repositories --repository-names 3dvista-kjb --query 'repositories[0].repositoryUri' --output text)
        echo "ECR Repository URI: $REPO_URI"
        echo "::set-output name=repository-url::$REPO_URI"

    - name: Tag and push Docker image to ECR
      if: steps.ecr-repo-url.outputs.repository-url != ''
      run: |
        docker tag 3dvista:latest ${{ steps.ecr-repo-url.outputs.repository-url }}:latest
        docker push ${{ steps.ecr-repo-url.outputs.repository-url }}:latest

    - name: Error - Repository URL is empty
      if: steps.ecr-repo-url.outputs.repository-url == ''
      run: |
        echo "Gagal mendapatkan ECR repository URL. Pastikan repo '3dvista-kjb' sudah dibuat di ECR."
        exit 1
